### ISSUE TITLE
index blockchain data to central database using demux model

### ISSUE THREAD

**Issue by manh-vv** [lecle/aloxide#5]
ref #3 

https://github.com/EOSIO/demux-js#data-flow

**Comment by flowersinthesand** [comment]
I think Demux fits well as a base of Aloxide's API gateway module and can help meet the following epics.

- > As a user I want to configure a data store that the api gateway will use to manage data so that I can use my favorite one or existing one from other applications
    - It would be solved by writing an ActionHandler integrated with ORM solution.
- > As a user I want to mirror a smart contract table into a corresponding table of the data store in the api gateway so that I can call sophisticated queries to the table in the api gateway
    - It would be solved by writing an ActionReader per blockchain software and building a new layer based on the layer Demux's ActionReaders provide.
    - Each ActionReader maybe needs to be included in the corresponding bridge module rather than API gateway module?

How do you think about that? also do you think Demux may affect the abstraction module too?

**Comment by manh-vv** [comment]
I have the same idea when mentioning the demux pattern.

**Comment by manh-vv** [comment]
close since it is solved in #21
